---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure munin-node is installed (RedHat).
  yum: pkg=munin-node state=installed enablerepo=epel
  when: ansible_os_family == 'RedHat'

- name: Ensure munin-node is installed (Debian).
  apt: pkg=munin-node state=installed
  when: ansible_os_family == 'Debian'

- name: Copy munin-node configuration.
  template: >
    src=munin-node.conf.j2
    dest=/etc/munin/munin-node.conf
    owner=root group=root mode=644
  notify: restart munin-node

# All this just to add the php_opcache plugin to Munin ...
- name: Download contributed Munin plugins.
  git:
    dest: /etc/munin/contrib
    repo: https://github.com/munin-monitoring/contrib.git

- name: Ensure the php_opcache plugin for Munin is executable.
  file:
    path: /etc/munin/contrib/plugins/php/php_opcache
    mode: "a+x"

- name: Generate plugin configuration.
  template: >
    src=plugin-conf.j2
    dest=/etc/munin/plugin-conf.d/ansible.conf
    owner=root group=root mode=644
  notify: restart munin-node

- name: Enable the php_opcache plugin.
  file:
    path: "{{ munin_plugin_dest_path }}/php_opcache"
    src: /etc/munin/contrib/plugins/php/php_opcache
    state: link
  notify: restart munin-node

- name: Enable additional plugins.
  file: >
    path={{ munin_plugin_dest_path }}{{ item.name }}
    src={{ munin_plugin_src_path }}{{ item.plugin | default( item.name ) }}
    state=link
  with_items: munin_node_plugins
  notify: restart munin-node

- name: Ensure munin-node is running.
  service: name=munin-node state=started enabled=yes
