---
## Basic settings
web_user: drupal
# These directories will be owned by the web user. Values are file modes.
web_base_dir: /opt/drupal
web_dirs:
  repos: "0700"
  sites: "02755"
  files: "02775"
# It is a little kludgy to set this here.
web_server_group: www-data

## Apache settings
# Do not create vhost files. I will do that manually.
apache_create_vhosts: false
apache_mods_enabled:
  - headers.load
  - rewrite.load
  - ssl.load

## MySQL settings
# Memory settings (default values optimized ~512MB RAM).
mysql_key_buffer_size: "16M"
mysql_max_allowed_packet: "16M"
mysql_myisam_sort_buffer_size: "16M"

## PHP settings
php_memory_limit: "128M"
php_max_execution_time: "30"
php_upload_max_filesize: "32M"
php_date_timezone: "America/New_York"
php_enable_php_fpm: true
php_enable_apc: false
php_short_open_tag: true
php_default_version_debian: "7.2"
php_mysql_package: php7.2-mysql

## Git settings
# Only install git, no extra packages.
git_packages:
  - git

# Databases. The corresponding users are defined in passwords.yml.
mysql_databases:
  - name: 3mile
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1
  - name: amcbostondev
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1
  - name: 200doc
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1

munin_hosts:
  - {
    name: "{{ hostname }}",
    address: "127.0.0.1",
    extra: ["use_node_name yes"]
    }

# Cache size for APC or OPCache
php_apc_shm_size: "256M"

php_enable_opcache: true

# This is used for the update option on the git module.
drush_keep_updated : yes
