---
## Basic settings
# The hostname can be overridden in the inventory file. The value set here will be used by vagrant.
hostname: arachne.dev
web_user: drupal
# These directories will be owned by the web user. Values are file modes.
web_base_dir: /opt/drupal
web_dirs:
  repos: "0700"
  sites: "02755"
  files: "02775"
# It is a little kludgy to set this here.
web_server_group: www-data

## Apache settings
# Do not create vhost files. I will do that manually.
apache_create_vhosts: false

## MySQL settings
# Memory settings (default values optimized ~512MB RAM).
mysql_key_buffer_size: "16M"
mysql_max_allowed_packet: "16M"
mysql_myisam_sort_buffer_size: "16M"

## PHP settings
php_memory_limit: "128M"
php_max_execution_time: "30"
php_upload_max_filesize: "32M"
php_date_timezone: "America/New_York"
php_enable_php_fpm: true
php_enable_apc: false
php_short_open_tag: true

## Git settings
# Only install git, no extra packages.
git_packages:
  - git

# Databases. The corresponding users are defined in passwords.yml.
mysql_databases:
  - name: 3mile
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1
  - name: amcbostondev
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1

drupal_sites:
  - { name: 3mile, repo: ~/arachne/sites/3mile.org }
  - { name: amcbostondev, repo: ~/arachne/sites/amcbostondev.org }
