---
- hosts: all
  # gather_facts: no

  vars_files:
  - vars/main.yml
  - vars/passwords.yml

  roles:
    - git
    - apache
    - mysql
    - php
    - php-mysql
    - composer
    - drush
    # - munin
    # - munin-node

  tasks:
