---
- hosts: all
  # gather_facts: no

  vars_files:
  - vars/main.yml
  - vars/passwords.yml

  pre_tasks:
    - name: Set the hostname.
      hostname: name={{ hostname }}
      when: hostname is defined and hostname != 'skip'

  roles:
    - git
    - apache
    - mysql
    - php
    - php-mysql
    - composer
    - drush
    # - munin
    # - munin-node

  tasks:
